const person_role = {
    "yến khoa": ["bạn", "tớ"],
    "anh khoa": ["bạn", "tớ"],
    "long thạch": ["bạn", "tớ"],
    "nhật hưng": ["bạn", "tớ"],
    "thanh nhân": ["bạn", "tớ"],
    "tường an": ["bạn", "tớ"],
    "hữu thịnh": ["bạn", "tớ"],
    "minh nhật": ["bạn", "tớ"],
    "nhật linh": ["bạn", "tớ"],
    "thiên kim": ["bạn", "tớ"],
    "trà my": ["bạn", "tớ"],
    "cẩm tiên": ["bạn", "tớ"],
    "tiến phát": ["bạn", "tớ"],
    "nhật hoài": ["bạn", "tớ"],
    "thành trung": ["bạn", "tớ"],
    "thái sơn": ["bạn", "tớ"],
    "minh thư": ["bạn", "tớ"],
    "bích vân": ["bạn", "tớ"],
    "minh anh": ["bạn", "tớ"],
    "thanh tân": ["bạn", "tớ"],
    "quốc an": ["bạn", "tớ"],
    "gia an": ["bạn", "tớ"],
    "quốc khánh": ["bạn", "tớ"],
    "hoàng sang": ["bạn", "tớ"],
    "thảo phương": ["bạn", "tớ"],
    "minh tùng": ["bạn", "tớ"],
    "ngọc nhân": ["bạn", "tớ"],
    "gia bách": ["bạn", "tớ"],
    "thủy tiên": ["bạn", "tớ"],
    "bình minh": ["bạn", "tớ"],
    "ngọc bảo": ["anh", "em"],
    "bảo": ["anh", "em"],
    "khanh": ["anh", "em"],
    "hoàng tuấn": ["anh", "em"],
    "phạm khanh": ["anh", "em"],
    "văn phong": ["anh", "em"],
    "ngọc hiền": ["chị", "em"],
    "mỹ huyền": ["chị", "em"],
    "nguyên ngọc": ["chị", "em"],
    "thùy dương": [1, null],
};


export default person_role;